# Generated by Django 2.2.3 on 2019-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
